import fs from "node:fs/promises";
import path from "node:path";
import esbuild from "esbuild";

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function buildCategory(category: string) {
  const categoryDir = path.join(process.cwd(), "src", category);
  if (!(await exists(categoryDir))) {
    return;
  }

  console.log(`[Builder] Compiling ruleset category: ${category}`);

  const items = await fs.readdir(categoryDir, { withFileTypes: true });
  const courierDirs = items.filter(item => item.isDirectory()).map(item => item.name);

  const importStatements: string[] = [];
  const ruleDeclarations: string[] = [];

  for (const courier of courierDirs) {
    const courierDir = path.join(categoryDir, courier);

    // Read JSON metadata and rules
    const metadataPath = path.join(courierDir, "_.json");
    if (!(await exists(metadataPath))) {
      console.warn(`[Builder] Skip: missing metadata _.json in ${courierDir}`);
      continue;
    }

    const metadata = JSON.parse(await fs.readFile(metadataPath, "utf-8"));
    const domains = metadata.domains || [];
    const name = metadata.name || courier;

    // Load static rules
    const statusRules: Record<string, any> = {};

    const deliveredPath = path.join(courierDir, "delivered.json");
    if (await exists(deliveredPath)) {
      statusRules.delivered = JSON.parse(await fs.readFile(deliveredPath, "utf-8"));
    }

    const deliveringPath = path.join(courierDir, "delivering.json");
    if (await exists(deliveringPath)) {
      statusRules.arriving = JSON.parse(await fs.readFile(deliveringPath, "utf-8"));
    }

    const exceptionPath = path.join(courierDir, "exception.json");
    if (await exists(exceptionPath)) {
      statusRules.exception = JSON.parse(await fs.readFile(exceptionPath, "utf-8"));
    }

    const trackingPath = path.join(courierDir, "tracking.json");
    let tracking: any = undefined;
    if (await exists(trackingPath)) {
      tracking = JSON.parse(await fs.readFile(trackingPath, "utf-8"));
    }

    // Check for custom parser file
    const parserPath = path.join(courierDir, "parser.ts");
    const hasParser = await exists(parserPath);

    const ruleObjStr = JSON.stringify({
      id: courier,
      name,
      domains,
      statusRules: Object.keys(statusRules).length > 0 ? statusRules : undefined,
      tracking
    }, null, 2);

    if (hasParser) {
      // Import the custom parser function
      const importName = `${courier}_parser`;
      importStatements.push(`import { parse as ${importName} } from "./${category}/${courier}/parser";`);

      // Inject parse callback into the exported rule object
      const objectWithParser = ruleObjStr.replace(
        /\n}$/,
        `,\n  parse: ${importName}\n}`
      );
      ruleDeclarations.push(objectWithParser);
    } else {
      ruleDeclarations.push(ruleObjStr);
    }
  }

  // Create temporary entry point TS file
  const tempEntryPath = path.join(process.cwd(), "src", `_tmp_${category}.ts`);
  const fileContent = `// Automatically generated by build.ts - DO NOT EDIT DIRECTLY
${importStatements.join("\n")}

export const rules = [
  ${ruleDeclarations.join(",\n  ")}
];

export default rules;
`;

  await fs.writeFile(tempEntryPath, fileContent, "utf-8");

  const distDir = path.join(process.cwd(), "dist");
  await fs.mkdir(distDir, { recursive: true });

  const outputJsPath = path.join(distDir, `${category}.js`);

  try {
    // Compile and bundle with esbuild
    await esbuild.build({
      entryPoints: [tempEntryPath],
      bundle: true,
      minify: true,
      sourcemap: false,
      platform: "node",
      target: "node20",
      format: "cjs", // CommonJS is easily loaded by VM
      outfile: outputJsPath
    });

    console.log(`[Builder] Successfully built category '${category}' -> ${outputJsPath}`);
  } catch (err) {
    console.error(`[Builder] Failed to compile category '${category}':`, err);
  } finally {
    // Clean up temporary file
    await fs.unlink(tempEntryPath).catch(() => { });
  }
}

async function main() {
  const categories = ["parcel", "order", "return"];
  for (const cat of categories) {
    await buildCategory(cat);
  }
}

main().catch(console.error);
