import fs from "node:fs/promises";
import path from "node:path";
import esbuild from "esbuild";

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function buildCategory(category: string) {
  const categoryDir = path.join(process.cwd(), "src", category);
  if (!(await exists(categoryDir))) {
    return;
  }

  console.log(`[Builder] Compiling ruleset category: ${category}`);

  const items = await fs.readdir(categoryDir, { withFileTypes: true });
  const tsFiles = items
    .filter(item => item.isFile() && item.name.endsWith(".ts") && !item.name.startsWith("_"))
    .map(item => item.name);

  const importStatements: string[] = [];
  const ruleNames: string[] = [];

  for (const filename of tsFiles) {
    const ruleName = path.basename(filename, ".ts");
    const importName = `${ruleName}_rule`;
    
    // Import the default export from the TS file
    importStatements.push(`import ${importName} from "./${category}/${ruleName}";`);
    ruleNames.push(importName);
  }

  if (ruleNames.length === 0) {
    console.log(`[Builder] Category '${category}' has no rules. Skipping.`);
    return;
  }

  // Create temporary entry point TS file
  const tempEntryPath = path.join(process.cwd(), "src", `_tmp_${category}.ts`);
  const fileContent = `// Automatically generated by build.ts - DO NOT EDIT DIRECTLY
${importStatements.join("\n")}

export const rules = [
  ${ruleNames.join(",\n  ")}
];

export default rules;
`;

  await fs.writeFile(tempEntryPath, fileContent, "utf-8");

  const distDir = path.join(process.cwd(), "dist");
  await fs.mkdir(distDir, { recursive: true });

  const outputJsPath = path.join(distDir, `${category}.js`);

  try {
    // Compile and bundle with esbuild
    await esbuild.build({
      entryPoints: [tempEntryPath],
      bundle: true,
      minify: true,
      sourcemap: false,
      platform: "node",
      target: "node20",
      format: "cjs", // CommonJS is easily loaded by VM
      outfile: outputJsPath
    });

    console.log(`[Builder] Successfully built category '${category}' -> ${outputJsPath}`);
  } catch (err) {
    console.error(`[Builder] Failed to compile category '${category}':`, err);
  } finally {
    // Clean up temporary file
    await fs.unlink(tempEntryPath).catch(() => { });
  }
}

async function main() {
  const categories = ["parcel", "order", "return", "dunning"];
  for (const cat of categories) {
    await buildCategory(cat);
  }
}

main().catch(console.error);
